//mod number_guess_game;
//mod for_loops;
//mod ownership;
//mod structs;
//mod enums;
//mod matches;
//mod vectors;
//mod strings;
//mod hashmaps;
//mod panics;
//mod generics;
//mod lifetime;
//mod closure;
//mod iter;
//mod concurrent;
//mod mutex;
//mod oop;
//mod iflet;
//mod pattern;
mod unsafecode;

fn main() {
    //number_guess_game::run();
    //for_loops::run();
    //ownership::run();
    //structs::run();
    //enums::run();
    //matches::run();
    //vectors::run();
    //strings::run();
    //hashmaps::run();
    //panics::run();
    //generics::run();
    //lifetime::run();
    //closure::run();
    //iter::run();
    //concurrent::run();
    //concurrent::channel_run();
    //mutex::run();
    //oop::run();
    //iflet::run();
    //pattern::run();
    unsafecode::run();
}
